config/routes.rb
Rails.application.routes.draw do
 
  resources :notes do
    resources :comments, only: [:new, :create, :show, :edit, :update, :destroy]
  end
  get 'home/index'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
   }

   delete 'notes/:id', to: 'notes#destroy', as: 'delete_note'
   get 'notes', to: 'notes#index', as: 'index_note'
   delete 'notes/:note_id/comments/:id', to: 'comments#destroy', as: 'delete_comment'
   put '/notes/:note_id/comments/:id', to: 'comments#update', as: 'update_comment' 
        
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"

end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :user
  has_many :comments
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :authorize_admin, only: [:new, :create, :update, :edit, :destroy] 
  before_action :set_note, only: [:show, :edit, :update, :destroy]
  # before_action only: [:new, :create, :update, :edit, :destroy] do
  #   authorize_request(["admin"])
  #  end
 

  # GET /notes or /notes.json
  def index
    @notes = Note.all         
  end

  # GET /notes/1 or /notes/1.json
  def show       
    @note = Note.find(params[:id])
    @comments = @note.comments
  end

  # GET /notes/new
  def new
    @note = Note.new
   
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes or /notes.json
  def create
    @note = Note.new(note_params)   
    @note.user = current_user   

      respond_to do |format|
        if @note.save
          format.html { redirect_to @note, notice: "Noticia creada exitosamente." }
          format.json { render :show, status: :created, location: @note }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @note.errors, status: :unprocessable_entity }
        end
      end   
  end

  # PATCH/PUT /notes/1 or /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: "Noticia actualizada exitosamente." }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1 or /notes/1.json
  def destroy
    @note.destroy

    respond_to do |format|
      format.html { redirect_to home_index_path, notice: "Noticia eliminada exitosamente." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def note_params
      params.require(:note).permit(:title, :content, :image)
    end

    def authorize_admin
      unless current_user.admin?
        redirect_to notes_path, notice: "No estás autorizado a crear noticias ."
      end
    end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_form.html.erb
<%= form_with(model: note) do |form| %>
  <% if note.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(note.errors.count, "error") %> No se pudo grabar la noticia</h2>

      <ul>
        <% note.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %> 

  <div class="container mt-5">
    <div class="mb-3 ">
      <%= form.label :imagen, style: "display: block", class:"form-label" %>
      <%= form.text_field :image, class:"form-control" %>
    </div>

    <div class="mb-3">
      <%= form.label :titulo, style: "display: block" %>    
      <%= form.text_field :title, class:"form-control" %>
    </div>

    <div class="mb-3">    
      <%= form.label :contenido, style: "display: block", class:"form-label" %> 
      <%= form.text_area :content, class: "form-control"%>
     </div>    

    <div>      
      <%=  form.hidden_field current_user.role %>
    </div><br>

    <div class="mt-3">
      <%= form.submit %>
    </div>
  </div>
<% end %>

app/views/notes/_index.html.erb
<p style="color: green"><%= notice %></p>


<div id="notes" class="row row-cols-1 row-cols-md-3 g-4">
  <% @notes.each do |note| %> 
    <div class="col"> 
      <%= render note %>          
    </div>
  </div>
  <% end %>
</div>

app/views/notes/_note.html.erb
 
   
    <div id="<%= dom_id note %>"> 
     <div class="card">
      <%= image_tag( note.image , class: "card-img-top") %>
      <div class="card-body">
        <h5 class="card-title text-start"> <p><strong></strong><%= note.title %></p></h5>
        <p class="card-text text-start"> <p><strong></strong><%= note.content %></p></p> 
      </div>
      <div class= "ver_noticia text-center">
        <%= link_to "Ver noticia", note %>    
      </div>
    </div>
  

app/views/notes/edit.html.erb
<div class="container">  
   <h1>Editar Noticia</h1>
    <%= render "form", note: @note %>
 </div>
 <div class="container mt-5">    
       <%= link_to "Show this note", @note, class: "nav_item" %> 
       <%= link_to "Back to notes", notes_path, class: "nav_item" %>     
 </div>
 

app/views/notes/new.html.erb
<div class="container">
    <h1>Crear Noticia</h1>
    <%= render "form", note: @note %>
</div>
    <br>
<div class="container mt-3 text-center">    
    <%= link_to "Volver a Noticias", home_index_path %>  
</div>

app/views/notes/show.html.erb
<div class="container">
  <p style="color: green"><%= notice %></p>

  <%= render partial: 'note', locals: { note: @note } %>

 <nav class="nav">
  

    <% if current_user.admin? %> 
      <%= button_to "Eliminar", delete_note_path(@note), method: :delete, class: "nav-link" %>
      <%= link_to "Editar", edit_note_path(@note), class: "nav-link"%>      
    <%end%>
    <% if user_signed_in? %>   
      <%= link_to "Comentar", new_note_comment_path(@note), class: "nav-link" %>
    <%end%>   
   

      <%= link_to "Volver a noticias", home_index_path, class: "nav-link" %>
 </nav>
 
  <div class="container mt-5">
    <h5>Comentarios</h5><br/>
      <div id="comments">
        <% @comments.each do |comment| %>
          <%= render comment %>
          <p>
            <%= link_to "Ver", note_comment_path(@note, comment), class: "nav-link" %>
          </p>
        <% end %>
      </div> 
  </div>  
</div>